name: Check Installs

on:
  push:
  workflow_dispatch:

jobs:
  check-installs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run check-installs.sh
        run: bash check-installs.sh

  check-installs-actions-runner:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/actions/actions-runner:latest
    steps:
      - uses: actions/checkout@v4

      - name: Run check-installs.sh
        run: bash check-installs.sh
